import { BuilderData } from "@/features/builder/types";
import { defaultBrandPreset } from "@/features/builder/default-brand-preset";

const demoMenuIconUrl =
  "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=240&q=80";
const demoMenuBannerUrl =
  "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=960&q=80";
const demoMenuCardUrl =
  "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=320&q=80";

export const mockBuilderData: BuilderData = {
  header: {
    username: defaultBrandPreset.username,
    publicHandle: defaultBrandPreset.username,
    displayName: defaultBrandPreset.brandName,
    tagline: defaultBrandPreset.tagline,
    showPublicHandle: true,
    shareTitle: "",
    shareDescription: "",
    shareImageUrl: "",
    avatarUrl: defaultBrandPreset.avatarUrl,
    heroImageUrl: defaultBrandPreset.heroImageUrl,
    layout: "classic",
    titleMode: "display_name",
    heroTextAlign: "center",
    heroOverlay: true,
    heroOverlayStrength: 0.35,
    matchThemeToHero: false,
  },
  theme: defaultBrandPreset.theme,
  text: {
    intro: defaultBrandPreset.intro,
    body: defaultBrandPreset.body,
    footerEnabled: false,
    footerText: "Powered by Link-in-Bio Builder",
  },
  buttonStyle: {
    uppercase: false,
    shadow: true,
    style: "solid",
    shadowLevel: 2,
  },
  socials: [
    {
      id: "social-instagram",
      platform: "instagram",
      url: defaultBrandPreset.socialUrls.instagram,
      enabled: true,
    },
    {
      id: "social-youtube",
      platform: "youtube",
      url: defaultBrandPreset.socialUrls.youtube,
      enabled: true,
    },
    {
      id: "social-x",
      platform: "x",
      url: defaultBrandPreset.socialUrls.x,
      enabled: true,
    },
  ],
  links: [
    {
      id: "link-01",
      contentType: "link",
      title: defaultBrandPreset.buttonLabels.primary,
      url: "https://example.com/primary",
      description: "Route visitors to your highest-priority business action.",
      buttonStyle: "icon-left",
      enabled: true,
      settings: {
        prioritize: true,
        thumbnailUrl: "/placeholders/link-thumbnail-default.svg",
        locked: false,
        style: "icon_left",
        buttonStyle: "icon-left",
        textAlign: "left",
        bannerRatio: "3:1",
        imageAspect: "3:1",
        imageFit: "cover",
        imageUrl: "",
        iconImageUrl: demoMenuIconUrl,
        backgroundImageUrl: "",
        preserveLineBreaks: true,
        openInNewTab: true,
        showBorder: true,
        textPanelContent: "",
      },
    },
    {
      id: "link-02",
      contentType: "link",
      title: defaultBrandPreset.buttonLabels.secondary,
      url: "https://example.com/secondary",
      description: "Share your core services, offers, or packages.",
      buttonStyle: "text-only",
      enabled: true,
      settings: {
        prioritize: false,
        locked: false,
        style: "text_only",
        buttonStyle: "text-only",
        textAlign: "left",
        bannerRatio: "3:1",
        imageAspect: "3:1",
        imageFit: "cover",
        imageUrl: "",
        iconImageUrl: "",
        backgroundImageUrl: "",
        preserveLineBreaks: true,
        openInNewTab: true,
        showBorder: true,
        textPanelContent: "",
      },
    },
    {
      id: "link-image-full-01",
      contentType: "link",
      title: "Featured Launch",
      url: "https://example.com/featured",
      description: "Highlight one important campaign with a full image button.",
      buttonStyle: "image-full",
      enabled: true,
      settings: {
        prioritize: false,
        locked: false,
        style: "image_banner",
        buttonStyle: "image-full",
        textAlign: "left",
        bannerRatio: "3:1",
        imageAspect: "3:1",
        imageFit: "cover",
        imageUrl: "",
        iconImageUrl: "",
        backgroundImageUrl: demoMenuBannerUrl,
        preserveLineBreaks: true,
        openInNewTab: true,
        showBorder: true,
        textPanelContent: "",
      },
    },
    {
      id: "link-text-panel-01",
      contentType: "link",
      title: "Studio Notes",
      url: "https://example.com/notes",
      description: "A text-first panel for longer copy.",
      body: "Opening hours\nMonday-Friday, 9:00-18:00\nBookings by appointment.",
      buttonStyle: "text-panel",
      enabled: true,
      settings: {
        prioritize: false,
        locked: false,
        style: "text_panel",
        buttonStyle: "text-panel",
        textAlign: "left",
        bannerRatio: "3:1",
        imageAspect: "3:1",
        imageFit: "cover",
        imageUrl: "",
        iconImageUrl: "",
        backgroundImageUrl: "",
        preserveLineBreaks: true,
        openInNewTab: true,
        showBorder: true,
        body: "Opening hours\nMonday-Friday, 9:00-18:00\nBookings by appointment.",
        textPanelContent: "Opening hours\nMonday-Friday, 9:00-18:00\nBookings by appointment.",
      },
    },
    {
      id: "link-03",
      contentType: "discount",
      title: "โปรสมาชิกใหม่",
      url: "https://bn9.one",
      description: "คัดลอกโค้ดแล้วกดไปใช้งานต่อได้เลย",
      buttonStyle: "card-left-image",
      enabled: true,
      discount: {
        type: "discount_code",
        cardTitle: "โปรสมาชิกใหม่",
        cardThumbnail: "/placeholders/link-thumbnail-default.svg",
        layout: "featured",
        modalTitle: "รับสิทธิ์โปรสมาชิกใหม่",
        modalHeroImage: "/placeholders/link-thumbnail-default.svg",
        modalDescription: "คัดลอกโค้ดแล้วกดไปใช้งานต่อได้เลย",
        discountCode: "BN9NEW",
        copyButtonLabel: "คัดลอกโค้ด",
        ctaButtonLabel: "ไปที่เว็บ",
        destinationUrl: "https://bn9.one",
        dismissible: true,
        codeLock: {
          enabled: false,
        },
        analyticsHooks: {
          trackModalOpen: true,
          trackCodeCopy: true,
          trackCtaClick: true,
        },
      },
      settings: {
        prioritize: false,
        locked: true,
        lockMessage: "Private access",
        style: "media_card",
        buttonStyle: "card-left-image",
        textAlign: "left",
        bannerRatio: "3:1",
        imageAspect: "3:1",
        imageFit: "cover",
        imageUrl: demoMenuCardUrl,
        iconImageUrl: "",
        backgroundImageUrl: "",
        preserveLineBreaks: true,
        openInNewTab: true,
        showBorder: true,
        textPanelContent: "",
        schedule: {
          startAt: "2026-04-01T00:00",
        },
      },
    },
    {
      id: "promo-gallery-01",
      contentType: "promo_gallery",
      title: "โปรโมชั่นแนะนำ",
      url: "",
      description: "แกลเลอรีโปรโมชัน",
      enabled: true,
      promoGallery: {
        type: "promo_gallery",
        title: "โปรโมชั่นแนะนำ",
        description: "เลื่อนเพื่อดูโปรทั้งหมด",
        items: [
          {
            id: "promo-item-01",
            imageUrl: "/placeholders/link-thumbnail-default.svg",
            title: "โปรสล็อตรายสัปดาห์",
            description: "รับโบนัสเพิ่มสูงสุด 20%",
            badge: "HOT",
            conditions: [
              { id: "promo-c-01", label: "ยอดฝากขั้นต่ำ", value: "100 บาท" },
              { id: "promo-c-02", label: "เทิร์นโอเวอร์", value: "5 เท่า" },
            ],
            ctaLabel: "ดูรายละเอียด",
            ctaUrl: "https://example.com/promo",
            openInNewTab: true,
            active: true,
          },
        ],
      },
      settings: {
        prioritize: false,
        locked: false,
        style: "media_card",
        buttonStyle: "card-left-image",
        textAlign: "left",
        bannerRatio: "3:1",
        imageAspect: "3:1",
        imageFit: "cover",
        imageUrl: demoMenuCardUrl,
        iconImageUrl: "",
        backgroundImageUrl: "",
        preserveLineBreaks: true,
        openInNewTab: true,
        showBorder: true,
        textPanelContent: "",
      },
    },
    {
      id: "external-form-01",
      contentType: "external_form",
      title: "แบบฟอร์มภายนอก",
      url: "https://docs.google.com/forms/",
      description: "กรอกข้อมูลผ่าน Google Form",
      enabled: true,
      externalForm: {
        type: "external_form",
        title: "แบบฟอร์มภายนอก",
        description: "กรอกข้อมูลผ่าน Google Form",
        formUrl: "https://docs.google.com/forms/",
        openMode: "new_tab",
        embedHtml: "",
        ctaLabel: "เปิดฟอร์ม",
        closeLabel: "ปิด",
        enabled: true,
        showOpenInBrowserButton: true,
      },
      settings: {
        prioritize: false,
        locked: false,
        style: "icon_left",
        buttonStyle: "icon-left",
        textAlign: "left",
        bannerRatio: "3:1",
        imageAspect: "3:1",
        imageFit: "cover",
        imageUrl: "",
        iconImageUrl: "",
        backgroundImageUrl: "",
        preserveLineBreaks: true,
        openInNewTab: true,
        showBorder: true,
        textPanelContent: "",
      },
    },
  ],
};
