import {
  BarChart3,
  Blocks,
  FileText,
  FormInput,
  Palette,
  Settings,
} from "lucide-react";

import type {
  AnalyticsTimeRange,
  ButtonStyle,
  DesignSettings,
  FormFieldType,
  LockType,
  MockAnalyticsRangeData,
  MockBlock,
  MockFormField,
  MockFormTemplate,
  MockLinkItem,
  MockPage,
  MockSubmissionRouting,
  PageLanguage,
  PageSettings,
  PageStatus,
  PageVisibility,
  QaChecklistGroup,
  SubmissionDestination,
  TextAlign,
} from "./types";

export const adminNavItems = [
  { label: "Pages", icon: FileText, active: true },
  { label: "Blocks", icon: Blocks, active: false },
  { label: "Design", icon: Palette, active: false },
  { label: "Forms", icon: FormInput, active: false },
  { label: "Analytics", icon: BarChart3, active: false },
  { label: "Settings", icon: Settings, active: false },
];

export const mockPages: MockPage[] = [
  {
    route: "/bn9/main",
    title: "Main landing",
    status: "active",
    detail: "Hero, offers, contact",
    headline: "Northfield Studio main experience",
    previewNote: "Primary public landing concept with hero and high-intent CTAs.",
  },
  {
    route: "/bn9/promo",
    title: "Promo page",
    status: "draft",
    detail: "Seasonal campaign",
    headline: "Limited campaign page",
    previewNote: "Focused promo flow with image-forward offers and urgency blocks.",
  },
  {
    route: "/bn9/support",
    title: "Support page",
    status: "mock",
    detail: "Static support concept",
    headline: "Support request hub",
    previewNote: "Mock support layout only; no deposit, withdraw, or ticket routes.",
  },
];

export const initialPageSettingsByRoute: Record<string, PageSettings> = {
  "/bn9/main": {
    pageTitle: "Northfield Studio main experience",
    publicHandle: "bn9",
    slug: "main",
    status: "Published",
    visibility: "Public",
    language: "English",
    timezone: "Asia/Bangkok",
    seoTitle: "Northfield Studio | Main Links",
    seoDescription:
      "Book consultations, view VIP menu, and open current support links from the BN9 main page.",
    socialTitle: "Northfield Studio main links",
    socialDescription: "Fast access to consultation, VIP offers, and support resources.",
    socialImageUrl: "https://support.bn9.one/mock-share/main.jpg",
    noindex: false,
  },
  "/bn9/promo": {
    pageTitle: "Limited campaign page",
    publicHandle: "bn9",
    slug: "promo",
    status: "Draft",
    visibility: "Hidden",
    language: "Thai",
    timezone: "Asia/Bangkok",
    seoTitle: "BN9 Promo | Limited Campaign",
    seoDescription:
      "A draft campaign page preview for limited offers, visual-only urgency blocks, and seasonal CTAs.",
    socialTitle: "Limited campaign preview",
    socialDescription: "Preview the mock promo flow before any real route or publishing exists.",
    socialImageUrl: "https://support.bn9.one/mock-share/promo.jpg",
    noindex: true,
  },
  "/bn9/support": {
    pageTitle: "Support request hub",
    publicHandle: "bn9",
    slug: "support",
    status: "Scheduled",
    visibility: "Password protected",
    language: "English",
    timezone: "Asia/Bangkok",
    seoTitle: "BN9 Support Hub",
    seoDescription:
      "Visual-only support hub preview with safe mock status, locked access styling, and no ticket routes.",
    socialTitle: "Support request hub",
    socialDescription: "A protected mock support preview for future account and help actions.",
    socialImageUrl: "",
    noindex: true,
  },
};

export const mockBlocks: MockBlock[] = [
  {
    id: "hero",
    label: "Hero Header",
    state: "enabled",
    detail: "Brand intro and avatar",
    previewTitle: "Hero Header",
    previewBody: "Brand avatar, page headline, short intro, and primary action area.",
    controls: ["Avatar style", "Headline size", "Hero media", "Intro alignment"],
  },
  {
    id: "buttons",
    label: "Button Group",
    state: "enabled",
    detail: "Primary links and CTAs",
    previewTitle: "Button Group",
    previewBody: "Stacked action buttons with icon, image, and text variants.",
    controls: ["Button density", "Icon placement", "Priority order", "Corner radius"],
  },
  {
    id: "form",
    label: "Form Block",
    state: "disabled",
    detail: "No endpoint wiring",
    previewTitle: "Form Block",
    previewBody: "Static form layout preview without submissions or API calls.",
    controls: ["Field spacing", "Required labels", "Submit copy", "Success state"],
  },
  {
    id: "embed",
    label: "Embed Post",
    state: "enabled",
    detail: "Static content preview",
    previewTitle: "Embed Post",
    previewBody: "Rich content slot for visual posts, announcements, or video embeds.",
    controls: ["Aspect ratio", "Caption style", "Media frame", "Content source"],
  },
  {
    id: "analytics",
    label: "Analytics Card",
    state: "disabled",
    detail: "Mock metrics only",
    previewTitle: "Analytics Card",
    previewBody: "Future private insight card with sample views, clicks, and CTR.",
    controls: ["Metric set", "Chart style", "Date range", "Privacy mode"],
  },
];

export const initialMockLinks: MockLinkItem[] = [
  {
    id: "book-consultation",
    title: "Book a Consultation",
    description: "Fast path for high-intent visitors who want a guided setup call.",
    body: "Choose a time with the studio team.\nConfirmation details stay in this mock only.",
    url: "https://support.bn9.one/consultation",
    actionLabel: "Open booking mock",
    enabled: true,
    prioritized: true,
    openInNewTab: true,
    buttonStyle: "icon-left",
    textAlignment: "left",
    imageUrl: "https://images.example/mock-consultation-icon.png",
    backgroundImageUrl: "https://images.example/mock-consultation-cover.jpg",
    schedulePublishDate: "2026-05-20",
    scheduleHideDate: "",
    lockType: "none",
    totalClicks: 1284,
    sevenDayClicks: 132,
    ctr: "12.4%",
  },
  {
    id: "vip-menu",
    title: "VIP Menu",
    description: "Image-forward menu concept for premium offers and private options.",
    body: "VIP members can scan current packages.\nThis is visual-only menu copy.",
    url: "https://support.bn9.one/vip",
    actionLabel: "Open VIP menu mock",
    enabled: true,
    prioritized: false,
    openInNewTab: false,
    buttonStyle: "image-full",
    textAlignment: "center",
    imageUrl: "https://images.example/mock-vip-icon.png",
    backgroundImageUrl: "https://images.example/mock-vip-cover.jpg",
    schedulePublishDate: "2026-05-22",
    scheduleHideDate: "",
    lockType: "age",
    totalClicks: 942,
    sevenDayClicks: 88,
    ctr: "10.1%",
  },
  {
    id: "support-request",
    title: "Support Request",
    description: "Private support flow concept with code-gated access.",
    body: "Describe the support need.\nA future version can route this into a real queue.",
    url: "support-request",
    actionLabel: "Open support mock",
    enabled: true,
    prioritized: false,
    openInNewTab: false,
    buttonStyle: "card-left-image",
    textAlignment: "left",
    imageUrl: "https://images.example/mock-support-icon.png",
    backgroundImageUrl: "https://images.example/mock-support-cover.jpg",
    schedulePublishDate: "2026-05-19",
    scheduleHideDate: "",
    lockType: "code",
    totalClicks: 603,
    sevenDayClicks: 47,
    ctr: "8.7%",
  },
  {
    id: "promo-banner",
    title: "Promo Banner",
    description: "Disabled banner draft with an intentionally empty URL state.",
    body: "Promo copy can sit here before a campaign URL exists.",
    url: "",
    actionLabel: "No URL set",
    enabled: false,
    prioritized: false,
    openInNewTab: false,
    buttonStyle: "text-only",
    textAlignment: "center",
    imageUrl: "https://images.example/mock-promo-icon.png",
    backgroundImageUrl: "https://images.example/mock-promo-cover.jpg",
    schedulePublishDate: "2026-05-10",
    scheduleHideDate: "2026-05-18",
    lockType: "none",
    totalClicks: 217,
    sevenDayClicks: 0,
    ctr: "0.0%",
  },
  {
    id: "announcement-panel",
    title: "Announcement Panel",
    description: "Long-form panel for updates that need multiple lines of context.",
    body: "Line one: service hours update.\nLine two: support response windows.\nLine three: follow the latest notice.",
    url: "https://support.bn9.one/announcements",
    actionLabel: "Read announcement mock",
    enabled: true,
    prioritized: false,
    openInNewTab: true,
    buttonStyle: "text-panel",
    textAlignment: "left",
    imageUrl: "https://images.example/mock-announcement-icon.png",
    backgroundImageUrl: "https://images.example/mock-announcement-cover.jpg",
    schedulePublishDate: "2026-05-21",
    scheduleHideDate: "",
    lockType: "sensitive",
    totalClicks: 451,
    sevenDayClicks: 71,
    ctr: "9.8%",
  },
];

export const mockFormTemplates: MockFormTemplate[] = [
  {
    id: "contact-form",
    title: "Contact Form",
    description: "General visitor message capture with name, email, and topic fields.",
    destinationLabel: "Mock inbox",
    enabled: true,
    privacyNote: "Visitor details stay inside this local lab preview.",
  },
  {
    id: "booking-form",
    title: "Booking Form",
    description: "Appointment request concept with date, phone, and preferred service.",
    destinationLabel: "Email notification mock",
    enabled: true,
    privacyNote: "Booking requests are visual-only and do not reserve time.",
  },
  {
    id: "support-form",
    title: "Support Form",
    description: "Safe support intake mock without deposit, withdraw, ticket, or API wiring.",
    destinationLabel: "Mock inbox",
    enabled: false,
    privacyNote: "No support request is sent from this lab form.",
  },
  {
    id: "lead-form",
    title: "Lead Form",
    description: "Lightweight lead qualification flow for campaigns and follow-up.",
    destinationLabel: "Google Sheets mock",
    enabled: true,
    privacyNote: "Sheet destination is a label only; no spreadsheet is contacted.",
  },
  {
    id: "custom-form",
    title: "Custom Form",
    description: "Flexible scratch form for future page-specific field combinations.",
    destinationLabel: "Webhook mock",
    enabled: true,
    privacyNote: "Webhook destination is visual-only and never called.",
  },
];

export const initialMockFormFieldsByForm: Record<string, MockFormField[]> = {
  "contact-form": [
    {
      id: "contact-name",
      label: "Name",
      placeholder: "Your name",
      type: "text",
      required: true,
      enabled: true,
      helpText: "Use a display name visitors recognize.",
      options: "",
      validationHint: "Name should not be empty.",
    },
    {
      id: "contact-email",
      label: "Email",
      placeholder: "you@example.com",
      type: "email",
      required: true,
      enabled: true,
      helpText: "Reply address for a future inbox workflow.",
      options: "",
      validationHint: "Must look like an email address.",
    },
    {
      id: "contact-topic",
      label: "Topic",
      placeholder: "Choose a topic",
      type: "select",
      required: false,
      enabled: true,
      helpText: "Options are mock-only.",
      options: "Consultation\nPartnership\nSupport",
      validationHint: "Optional select field.",
    },
    {
      id: "contact-message",
      label: "Message",
      placeholder: "How can we help?",
      type: "textarea",
      required: true,
      enabled: true,
      helpText: "Long text preview only.",
      options: "",
      validationHint: "Message should include context.",
    },
  ],
  "booking-form": [
    {
      id: "booking-name",
      label: "Full name",
      placeholder: "Customer name",
      type: "text",
      required: true,
      enabled: true,
      helpText: "Shown in the mock booking card.",
      options: "",
      validationHint: "Required booking name.",
    },
    {
      id: "booking-phone",
      label: "Phone",
      placeholder: "Preferred phone number",
      type: "phone",
      required: true,
      enabled: true,
      helpText: "No SMS or call is triggered.",
      options: "",
      validationHint: "Phone format hint only.",
    },
    {
      id: "booking-date",
      label: "Preferred date",
      placeholder: "Select a date",
      type: "date",
      required: false,
      enabled: true,
      helpText: "Calendar is visual-only.",
      options: "",
      validationHint: "Date should be in the future.",
    },
    {
      id: "booking-service",
      label: "Service",
      placeholder: "Choose service",
      type: "radio",
      required: true,
      enabled: true,
      helpText: "Radio options stay local.",
      options: "Consultation\nVIP setup\nSupport session",
      validationHint: "One mock service should be selected.",
    },
  ],
  "support-form": [
    {
      id: "support-email",
      label: "Account email",
      placeholder: "account@example.com",
      type: "email",
      required: true,
      enabled: true,
      helpText: "No support account lookup is performed.",
      options: "",
      validationHint: "Email hint only.",
    },
    {
      id: "support-category",
      label: "Support category",
      placeholder: "Choose a category",
      type: "select",
      required: true,
      enabled: true,
      helpText: "No deposit or withdraw routes are connected.",
      options: "Account\nPage access\nGeneral question",
      validationHint: "Category is required in the mock.",
    },
    {
      id: "support-attachment",
      label: "Attachment link",
      placeholder: "https://example.com/file",
      type: "file URL",
      required: false,
      enabled: true,
      helpText: "Paste a URL only; no upload is performed.",
      options: "",
      validationHint: "File URL helper only.",
    },
  ],
  "lead-form": [
    {
      id: "lead-name",
      label: "Lead name",
      placeholder: "Name",
      type: "text",
      required: true,
      enabled: true,
      helpText: "Used in the fake submission preview.",
      options: "",
      validationHint: "Lead name should be present.",
    },
    {
      id: "lead-email",
      label: "Lead email",
      placeholder: "lead@example.com",
      type: "email",
      required: true,
      enabled: true,
      helpText: "No email service is contacted.",
      options: "",
      validationHint: "Email hint only.",
    },
    {
      id: "lead-interest",
      label: "Interest level",
      placeholder: "Select interest",
      type: "checkbox",
      required: false,
      enabled: true,
      helpText: "Checkbox options are local text.",
      options: "Pricing\nDemo\nSupport",
      validationHint: "Optional choices.",
    },
  ],
  "custom-form": [
    {
      id: "custom-empty-label",
      label: "",
      placeholder: "Untitled field",
      type: "text",
      required: true,
      enabled: true,
      helpText: "Intentional empty label to show validation hint.",
      options: "",
      validationHint: "empty field label",
    },
    {
      id: "custom-notes",
      label: "Notes",
      placeholder: "Custom notes",
      type: "textarea",
      required: false,
      enabled: true,
      helpText: "Scratch textarea for the prototype.",
      options: "",
      validationHint: "Optional notes.",
    },
  ],
};

export const initialMockSubmissionRoutingByForm: Record<string, MockSubmissionRouting> = {
  "contact-form": {
    destination: "Mock inbox",
    mockInbox: true,
    emailNotification: false,
    googleSheets: false,
    webhook: false,
  },
  "booking-form": {
    destination: "Email notification mock",
    mockInbox: true,
    emailNotification: true,
    googleSheets: false,
    webhook: false,
  },
  "support-form": {
    destination: "Mock inbox",
    mockInbox: true,
    emailNotification: false,
    googleSheets: false,
    webhook: false,
  },
  "lead-form": {
    destination: "Google Sheets mock",
    mockInbox: true,
    emailNotification: false,
    googleSheets: true,
    webhook: false,
  },
  "custom-form": {
    destination: "Webhook mock",
    mockInbox: false,
    emailNotification: false,
    googleSheets: false,
    webhook: true,
  },
};

export const mockAnalyticsByRange: Record<AnalyticsTimeRange, MockAnalyticsRangeData> = {
  Today: {
    metrics: [
      { label: "Total views", value: "1,284", detail: "Mock page views", trend: "+8%" },
      { label: "Link clicks", value: "312", detail: "Local click sample", trend: "+4%" },
      { label: "Click-through rate", value: "24.3%", detail: "Clicks / views", trend: "+1.2%" },
      { label: "Form submissions", value: "38", detail: "Fake submissions", trend: "+6" },
      { label: "Conversion rate", value: "3.0%", detail: "Completed action", trend: "+0.4%" },
      { label: "Top performing link", value: "VIP Menu", detail: "Highest CTR today", trend: "hot" },
      { label: "Top traffic source", value: "Instagram", detail: "Largest source", trend: "+11%" },
      { label: "Device split", value: "72% mobile", detail: "Mobile-heavy traffic", trend: "stable" },
    ],
    topLinks: [
      {
        id: "book-consultation",
        title: "Book a Consultation",
        clicks: 92,
        views: 365,
        ctr: "25.2%",
        conversions: 15,
        trend: "+6%",
        insight: "Consultation clicks are strongest after profile visits today.",
      },
      {
        id: "vip-menu",
        title: "VIP Menu",
        clicks: 104,
        views: 318,
        ctr: "32.7%",
        conversions: 12,
        trend: "+14%",
        insight: "VIP Menu has the highest CTR today.",
      },
      {
        id: "support-request",
        title: "Support Request",
        clicks: 48,
        views: 224,
        ctr: "21.4%",
        conversions: 7,
        trend: "+2%",
        insight: "Support Request gets most traffic from mobile.",
      },
      {
        id: "promo-banner",
        title: "Promo Banner",
        clicks: 21,
        views: 180,
        ctr: "11.7%",
        conversions: 2,
        trend: "-5%",
        insight: "Promo Banner dropped this range.",
      },
      {
        id: "announcement-panel",
        title: "Announcement Panel",
        clicks: 47,
        views: 197,
        ctr: "23.9%",
        conversions: 2,
        trend: "+3%",
        insight: "Announcement Panel holds steady as a secondary action.",
      },
    ],
    forms: [
      {
        id: "contact-form",
        title: "Contact Form",
        views: 156,
        starts: 62,
        submissions: 24,
        completionRate: "38.7%",
        dropOffHint: "Message field causes most exits",
        destination: "Mock inbox",
      },
      {
        id: "booking-form",
        title: "Booking Form",
        views: 121,
        starts: 58,
        submissions: 31,
        completionRate: "53.4%",
        dropOffHint: "Date selection is the soft drop-off",
        destination: "Email notification mock",
      },
      {
        id: "support-form",
        title: "Support Form",
        views: 94,
        starts: 34,
        submissions: 12,
        completionRate: "35.3%",
        dropOffHint: "Attachment URL is often skipped",
        destination: "Mock inbox",
      },
      {
        id: "lead-form",
        title: "Lead Form",
        views: 83,
        starts: 29,
        submissions: 17,
        completionRate: "58.6%",
        dropOffHint: "Low drop-off after email",
        destination: "Google Sheets mock",
      },
      {
        id: "custom-form",
        title: "Custom Form",
        views: 44,
        starts: 11,
        submissions: 5,
        completionRate: "45.5%",
        dropOffHint: "Untitled field needs cleanup",
        destination: "Webhook mock",
      },
    ],
    trafficSources: [
      { label: "Direct", value: 18, detail: "231 views" },
      { label: "Instagram", value: 34, detail: "437 views" },
      { label: "Facebook", value: 13, detail: "167 views" },
      { label: "TikTok", value: 16, detail: "205 views" },
      { label: "X", value: 4, detail: "51 views" },
      { label: "Search", value: 9, detail: "116 views" },
      { label: "QR Code", value: 6, detail: "77 views" },
    ],
    deviceSplit: [
      { label: "Mobile", value: 72, detail: "924 views" },
      { label: "Desktop", value: 21, detail: "270 views" },
      { label: "Tablet", value: 7, detail: "90 views" },
    ],
    regionSplit: [
      { label: "Thailand", value: 64, detail: "822 views" },
      { label: "Singapore", value: 12, detail: "154 views" },
      { label: "United States", value: 9, detail: "116 views" },
      { label: "Other", value: 15, detail: "192 views" },
    ],
    funnel: [
      { label: "Page view", value: 1284, percent: "100%" },
      { label: "Link click", value: 312, percent: "24%" },
      { label: "Form start", value: 194, percent: "15%" },
      { label: "Form submit", value: 38, percent: "3%" },
      { label: "Completed action", value: 24, percent: "2%" },
    ],
    miniChartLabels: ["09:00", "12:00", "15:00", "18:00"],
    rangeInsight: "Today is mobile-heavy, with VIP Menu leading short-session clicks.",
    insights: [
      "VIP Menu has the highest CTR today.",
      "Support Request gets most traffic from mobile.",
      "Booking Form has a higher completion rate than Contact Form.",
      "Promo Banner dropped this range.",
    ],
  },
  "7 days": {
    metrics: [
      { label: "Total views", value: "8,642", detail: "Mock weekly views", trend: "+12%" },
      { label: "Link clicks", value: "2,184", detail: "Local click sample", trend: "+9%" },
      { label: "Click-through rate", value: "25.3%", detail: "Clicks / views", trend: "+2.0%" },
      { label: "Form submissions", value: "246", detail: "Fake submissions", trend: "+31" },
      { label: "Conversion rate", value: "2.8%", detail: "Completed action", trend: "+0.3%" },
      { label: "Top performing link", value: "VIP Menu", detail: "Best weekly CTR", trend: "hot" },
      { label: "Top traffic source", value: "Instagram", detail: "Weekly leader", trend: "+18%" },
      { label: "Device split", value: "69% mobile", detail: "Mobile leads", trend: "stable" },
    ],
    topLinks: [
      {
        id: "book-consultation",
        title: "Book a Consultation",
        clicks: 648,
        views: 2310,
        ctr: "28.1%",
        conversions: 96,
        trend: "+10%",
        insight: "Book a Consultation converts strongly after repeat visits.",
      },
      {
        id: "vip-menu",
        title: "VIP Menu",
        clicks: 712,
        views: 2056,
        ctr: "34.6%",
        conversions: 82,
        trend: "+19%",
        insight: "VIP Menu has the highest CTR this week.",
      },
      {
        id: "support-request",
        title: "Support Request",
        clicks: 326,
        views: 1624,
        ctr: "20.1%",
        conversions: 41,
        trend: "+5%",
        insight: "Support Request gets most traffic from mobile.",
      },
      {
        id: "promo-banner",
        title: "Promo Banner",
        clicks: 184,
        views: 1338,
        ctr: "13.8%",
        conversions: 13,
        trend: "-8%",
        insight: "Promo Banner dropped this range.",
      },
      {
        id: "announcement-panel",
        title: "Announcement Panel",
        clicks: 314,
        views: 1314,
        ctr: "23.9%",
        conversions: 14,
        trend: "+7%",
        insight: "Announcement Panel supports return visitors.",
      },
    ],
    forms: [
      {
        id: "contact-form",
        title: "Contact Form",
        views: 978,
        starts: 402,
        submissions: 138,
        completionRate: "34.3%",
        dropOffHint: "Message field adds friction",
        destination: "Mock inbox",
      },
      {
        id: "booking-form",
        title: "Booking Form",
        views: 812,
        starts: 388,
        submissions: 212,
        completionRate: "54.6%",
        dropOffHint: "Date step performs well",
        destination: "Email notification mock",
      },
      {
        id: "support-form",
        title: "Support Form",
        views: 624,
        starts: 241,
        submissions: 84,
        completionRate: "34.9%",
        dropOffHint: "Attachment URL is optional but distracting",
        destination: "Mock inbox",
      },
      {
        id: "lead-form",
        title: "Lead Form",
        views: 536,
        starts: 232,
        submissions: 137,
        completionRate: "59.1%",
        dropOffHint: "Interest options help completion",
        destination: "Google Sheets mock",
      },
      {
        id: "custom-form",
        title: "Custom Form",
        views: 214,
        starts: 66,
        submissions: 27,
        completionRate: "40.9%",
        dropOffHint: "Empty label depresses completion",
        destination: "Webhook mock",
      },
    ],
    trafficSources: [
      { label: "Direct", value: 20, detail: "1,728 views" },
      { label: "Instagram", value: 36, detail: "3,111 views" },
      { label: "Facebook", value: 12, detail: "1,037 views" },
      { label: "TikTok", value: 14, detail: "1,210 views" },
      { label: "X", value: 3, detail: "259 views" },
      { label: "Search", value: 10, detail: "864 views" },
      { label: "QR Code", value: 5, detail: "432 views" },
    ],
    deviceSplit: [
      { label: "Mobile", value: 69, detail: "5,963 views" },
      { label: "Desktop", value: 24, detail: "2,074 views" },
      { label: "Tablet", value: 7, detail: "605 views" },
    ],
    regionSplit: [
      { label: "Thailand", value: 61, detail: "5,272 views" },
      { label: "Singapore", value: 14, detail: "1,210 views" },
      { label: "United States", value: 10, detail: "864 views" },
      { label: "Other", value: 15, detail: "1,296 views" },
    ],
    funnel: [
      { label: "Page view", value: 8642, percent: "100%" },
      { label: "Link click", value: 2184, percent: "25%" },
      { label: "Form start", value: 1329, percent: "15%" },
      { label: "Form submit", value: 246, percent: "3%" },
      { label: "Completed action", value: 168, percent: "2%" },
    ],
    miniChartLabels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    rangeInsight: "This week favors VIP Menu and Booking Form completion.",
    insights: [
      "VIP Menu has the highest CTR this week.",
      "Support Request gets most traffic from mobile.",
      "Booking Form has a higher completion rate than Contact Form.",
      "Promo Banner dropped this range.",
      "Instagram accounts for more than one-third of weekly traffic.",
    ],
  },
  "30 days": {
    metrics: [
      { label: "Total views", value: "31,880", detail: "Mock monthly views", trend: "+7%" },
      { label: "Link clicks", value: "7,842", detail: "Local click sample", trend: "+5%" },
      { label: "Click-through rate", value: "24.6%", detail: "Clicks / views", trend: "+0.6%" },
      { label: "Form submissions", value: "812", detail: "Fake submissions", trend: "+68" },
      { label: "Conversion rate", value: "2.5%", detail: "Completed action", trend: "-0.1%" },
      { label: "Top performing link", value: "Book a Consultation", detail: "Most conversions", trend: "+11%" },
      { label: "Top traffic source", value: "Direct", detail: "Monthly leader", trend: "+9%" },
      { label: "Device split", value: "66% mobile", detail: "Mobile leads", trend: "stable" },
    ],
    topLinks: [
      {
        id: "book-consultation",
        title: "Book a Consultation",
        clicks: 2546,
        views: 9028,
        ctr: "28.2%",
        conversions: 388,
        trend: "+11%",
        insight: "Book a Consultation drives the most completed actions this month.",
      },
      {
        id: "vip-menu",
        title: "VIP Menu",
        clicks: 2384,
        views: 7422,
        ctr: "32.1%",
        conversions: 241,
        trend: "+8%",
        insight: "VIP Menu remains the CTR leader across 30 days.",
      },
      {
        id: "support-request",
        title: "Support Request",
        clicks: 1248,
        views: 5890,
        ctr: "21.2%",
        conversions: 104,
        trend: "+4%",
        insight: "Support Request is consistent, especially on mobile.",
      },
      {
        id: "promo-banner",
        title: "Promo Banner",
        clicks: 642,
        views: 4920,
        ctr: "13.0%",
        conversions: 35,
        trend: "-12%",
        insight: "Promo Banner dropped this range.",
      },
      {
        id: "announcement-panel",
        title: "Announcement Panel",
        clicks: 1022,
        views: 4620,
        ctr: "22.1%",
        conversions: 44,
        trend: "+2%",
        insight: "Announcement Panel keeps a steady baseline.",
      },
    ],
    forms: [
      {
        id: "contact-form",
        title: "Contact Form",
        views: 3440,
        starts: 1320,
        submissions: 426,
        completionRate: "32.3%",
        dropOffHint: "Long message prompt causes exits",
        destination: "Mock inbox",
      },
      {
        id: "booking-form",
        title: "Booking Form",
        views: 2980,
        starts: 1412,
        submissions: 722,
        completionRate: "51.1%",
        dropOffHint: "Phone field performs better than email",
        destination: "Email notification mock",
      },
      {
        id: "support-form",
        title: "Support Form",
        views: 2104,
        starts: 818,
        submissions: 266,
        completionRate: "32.5%",
        dropOffHint: "Attachment link step is the largest drop",
        destination: "Mock inbox",
      },
      {
        id: "lead-form",
        title: "Lead Form",
        views: 1980,
        starts: 888,
        submissions: 515,
        completionRate: "58.0%",
        dropOffHint: "Lead Form completes cleanly",
        destination: "Google Sheets mock",
      },
      {
        id: "custom-form",
        title: "Custom Form",
        views: 722,
        starts: 204,
        submissions: 83,
        completionRate: "40.7%",
        dropOffHint: "Custom field labels need review",
        destination: "Webhook mock",
      },
    ],
    trafficSources: [
      { label: "Direct", value: 29, detail: "9,245 views" },
      { label: "Instagram", value: 28, detail: "8,926 views" },
      { label: "Facebook", value: 12, detail: "3,826 views" },
      { label: "TikTok", value: 11, detail: "3,507 views" },
      { label: "X", value: 4, detail: "1,275 views" },
      { label: "Search", value: 10, detail: "3,188 views" },
      { label: "QR Code", value: 6, detail: "1,913 views" },
    ],
    deviceSplit: [
      { label: "Mobile", value: 66, detail: "21,041 views" },
      { label: "Desktop", value: 26, detail: "8,289 views" },
      { label: "Tablet", value: 8, detail: "2,550 views" },
    ],
    regionSplit: [
      { label: "Thailand", value: 58, detail: "18,490 views" },
      { label: "Singapore", value: 16, detail: "5,101 views" },
      { label: "United States", value: 12, detail: "3,826 views" },
      { label: "Other", value: 14, detail: "4,463 views" },
    ],
    funnel: [
      { label: "Page view", value: 31880, percent: "100%" },
      { label: "Link click", value: 7842, percent: "25%" },
      { label: "Form start", value: 4642, percent: "15%" },
      { label: "Form submit", value: 812, percent: "3%" },
      { label: "Completed action", value: 552, percent: "2%" },
    ],
    miniChartLabels: ["W1", "W2", "W3", "W4"],
    rangeInsight: "30-day conversions are led by consultation and lead form flows.",
    insights: [
      "Book a Consultation drives the most completed actions this month.",
      "VIP Menu remains the best CTR link.",
      "Lead Form has a higher completion rate than Contact Form.",
      "Promo Banner dropped this range.",
    ],
  },
  "90 days": {
    metrics: [
      { label: "Total views", value: "94,210", detail: "Mock quarterly views", trend: "+16%" },
      { label: "Link clicks", value: "22,480", detail: "Local click sample", trend: "+12%" },
      { label: "Click-through rate", value: "23.9%", detail: "Clicks / views", trend: "-0.3%" },
      { label: "Form submissions", value: "2,184", detail: "Fake submissions", trend: "+204" },
      { label: "Conversion rate", value: "2.3%", detail: "Completed action", trend: "+0.2%" },
      { label: "Top performing link", value: "Book a Consultation", detail: "Quarter winner", trend: "+15%" },
      { label: "Top traffic source", value: "Direct", detail: "Durable source", trend: "+21%" },
      { label: "Device split", value: "64% mobile", detail: "Mobile leads", trend: "stable" },
    ],
    topLinks: [
      {
        id: "book-consultation",
        title: "Book a Consultation",
        clicks: 7488,
        views: 28120,
        ctr: "26.6%",
        conversions: 1164,
        trend: "+15%",
        insight: "Book a Consultation is the strongest long-range converter.",
      },
      {
        id: "vip-menu",
        title: "VIP Menu",
        clicks: 6884,
        views: 22690,
        ctr: "30.3%",
        conversions: 708,
        trend: "+10%",
        insight: "VIP Menu sustains the best long-range CTR.",
      },
      {
        id: "support-request",
        title: "Support Request",
        clicks: 3482,
        views: 17120,
        ctr: "20.3%",
        conversions: 284,
        trend: "+3%",
        insight: "Support Request gets most traffic from mobile.",
      },
      {
        id: "promo-banner",
        title: "Promo Banner",
        clicks: 1788,
        views: 12840,
        ctr: "13.9%",
        conversions: 96,
        trend: "-6%",
        insight: "Promo Banner dropped this range.",
      },
      {
        id: "announcement-panel",
        title: "Announcement Panel",
        clicks: 2838,
        views: 13440,
        ctr: "21.1%",
        conversions: 108,
        trend: "+5%",
        insight: "Announcement Panel performs best with direct traffic.",
      },
    ],
    forms: [
      {
        id: "contact-form",
        title: "Contact Form",
        views: 9920,
        starts: 3710,
        submissions: 1188,
        completionRate: "32.0%",
        dropOffHint: "Long text remains the main drop-off",
        destination: "Mock inbox",
      },
      {
        id: "booking-form",
        title: "Booking Form",
        views: 8720,
        starts: 4012,
        submissions: 2030,
        completionRate: "50.6%",
        dropOffHint: "Booking Form remains efficient",
        destination: "Email notification mock",
      },
      {
        id: "support-form",
        title: "Support Form",
        views: 6220,
        starts: 2310,
        submissions: 724,
        completionRate: "31.3%",
        dropOffHint: "Attachment link creates friction",
        destination: "Mock inbox",
      },
      {
        id: "lead-form",
        title: "Lead Form",
        views: 5640,
        starts: 2444,
        submissions: 1392,
        completionRate: "57.0%",
        dropOffHint: "Lead Form remains the cleanest flow",
        destination: "Google Sheets mock",
      },
      {
        id: "custom-form",
        title: "Custom Form",
        views: 2110,
        starts: 588,
        submissions: 214,
        completionRate: "36.4%",
        dropOffHint: "Custom Form needs field cleanup",
        destination: "Webhook mock",
      },
    ],
    trafficSources: [
      { label: "Direct", value: 32, detail: "30,147 views" },
      { label: "Instagram", value: 27, detail: "25,437 views" },
      { label: "Facebook", value: 11, detail: "10,363 views" },
      { label: "TikTok", value: 10, detail: "9,421 views" },
      { label: "X", value: 4, detail: "3,768 views" },
      { label: "Search", value: 11, detail: "10,363 views" },
      { label: "QR Code", value: 5, detail: "4,711 views" },
    ],
    deviceSplit: [
      { label: "Mobile", value: 64, detail: "60,294 views" },
      { label: "Desktop", value: 28, detail: "26,379 views" },
      { label: "Tablet", value: 8, detail: "7,537 views" },
    ],
    regionSplit: [
      { label: "Thailand", value: 57, detail: "53,700 views" },
      { label: "Singapore", value: 17, detail: "16,016 views" },
      { label: "United States", value: 13, detail: "12,247 views" },
      { label: "Other", value: 13, detail: "12,247 views" },
    ],
    funnel: [
      { label: "Page view", value: 94210, percent: "100%" },
      { label: "Link click", value: 22480, percent: "24%" },
      { label: "Form start", value: 13064, percent: "14%" },
      { label: "Form submit", value: 2184, percent: "2%" },
      { label: "Completed action", value: 1492, percent: "2%" },
    ],
    miniChartLabels: ["M1", "M2", "M3"],
    rangeInsight: "90-day mock data points to durable direct traffic and consultation conversions.",
    insights: [
      "Book a Consultation is the strongest long-range converter.",
      "VIP Menu sustains the best CTR over 90 days.",
      "Support Request gets most traffic from mobile.",
      "Booking Form has a higher completion rate than Contact Form.",
      "Promo Banner dropped this range.",
    ],
  },
};

export const buttonStyles: Array<{
  id: ButtonStyle;
  label: string;
  detail: string;
}> = [
  { id: "icon-left", label: "Icon left", detail: "Circular media with CTA text" },
  { id: "image-full", label: "Image full", detail: "Image-led button with overlay" },
  { id: "text-only", label: "Text only", detail: "Minimal typography button" },
  { id: "card-left-image", label: "Card left image", detail: "Compact card with media rail" },
  { id: "text-panel", label: "Text panel", detail: "Paragraph-first content panel" },
];

export const defaultDesignSettings: DesignSettings = {
  theme: "Studio Light",
  buttonStyle: "icon-left",
  radius: "14px",
  textAlignment: "left",
  imageSourceMode: "URL field",
  border: "Soft border",
  shadow: "Low shadow",
  spacing: "Comfortable",
  density: "Balanced",
  imageUrl: "https://images.example/mock-icon.png",
  backgroundImageUrl: "https://images.example/mock-cover.jpg",
  aspectRatio: "3:1",
  overlayOpacity: 42,
  textOverlay: true,
  fontWeight: "Semibold",
  title: "Priority support",
  description: "Fast access to the current help flow and account actions.",
  body: "Use this panel for longer menu copy.\nLine breaks stay visible in the preview.",
};

export const safeLabels = [
  "local mock state only",
  "local mock analytics only",
  "no submission",
  "no tracking",
  "no database read",
  "no Google Sheets",
  "no Supabase",
  "no save",
  "no publish",
  "no schema update",
  "no route loading",
  "no API calls",
];

export const qaSafetyGuardLabels = [
  "no save",
  "no publish",
  "no API calls",
  "no Supabase",
  "no Google Sheets",
  "no webhook call",
  "no tracking",
  "no public renderer changes",
];

export const qaChecklistGroups: QaChecklistGroup[] = [
  {
    title: "Navigation",
    items: [
      {
        label: "Admin UI V2 tab opens",
        expectedBehavior: "Selecting the lab tab renders the mock workspace without changing route data.",
        status: "Ready",
        note: "Lab tab shell only.",
      },
    ],
  },
  {
    title: "Page selection",
    items: [
      {
        label: "Mock pages update the workspace",
        expectedBehavior: "/bn9/main, /bn9/promo, and /bn9/support update local settings and previews.",
        status: "Manual check",
      },
    ],
  },
  {
    title: "Block selection",
    items: [
      {
        label: "Block manager changes inspector copy",
        expectedBehavior: "Selecting a block updates the editor and property inspector labels only.",
        status: "Mock only",
      },
    ],
  },
  {
    title: "Button style selector",
    items: [
      {
        label: "Style changes stay local",
        expectedBehavior: "Icon, image, text, card, and panel styles update the selected mock link preview.",
        status: "Ready",
      },
    ],
  },
  {
    title: "Link manager",
    items: [
      {
        label: "Selected link drives editor state",
        expectedBehavior: "Clicking a link card changes the design panel, preview, and inspector.",
        status: "Manual check",
      },
    ],
  },
  {
    title: "Link reorder",
    items: [
      {
        label: "Move controls reorder mock links",
        expectedBehavior: "Move up and down controls reorder only the local link array.",
        status: "Mock only",
      },
    ],
  },
  {
    title: "Prioritize one link",
    items: [
      {
        label: "Priority toggle remains exclusive",
        expectedBehavior: "Prioritizing one link clears priority from the other mock links.",
        status: "Ready",
      },
    ],
  },
  {
    title: "Page settings",
    items: [
      {
        label: "Settings update previews",
        expectedBehavior: "Title, handle, slug, status, visibility, language, and SEO values update cards only.",
        status: "Manual check",
      },
    ],
  },
  {
    title: "Mock publish flow",
    items: [
      {
        label: "Publish controls do not persist",
        expectedBehavior: "Save draft clears local dirty state; publish and schedule update local badges only.",
        status: "Safety guard",
        note: "No real save status bar or route update.",
      },
    ],
  },
  {
    title: "Form builder",
    items: [
      {
        label: "Template cards select mock forms",
        expectedBehavior: "Contact, booking, support, lead, and custom templates change local form state.",
        status: "Mock only",
      },
    ],
  },
  {
    title: "Field builder",
    items: [
      {
        label: "Field list and settings stay local",
        expectedBehavior: "Selecting, editing, enabling, requiring, and reordering fields changes mock state only.",
        status: "Manual check",
      },
    ],
  },
  {
    title: "Submission routing",
    items: [
      {
        label: "Routing toggles are labels only",
        expectedBehavior: "Mock inbox, email, Google Sheets, and webhook toggles never call external systems.",
        status: "Safety guard",
      },
    ],
  },
  {
    title: "Analytics range selector",
    items: [
      {
        label: "Time range changes mock analytics",
        expectedBehavior: "Today, 7 days, 30 days, and 90 days switch static metric sets and insight text.",
        status: "Mock only",
      },
    ],
  },
  {
    title: "Top link analytics selection",
    items: [
      {
        label: "Top link detail follows selection",
        expectedBehavior: "Selecting a top link updates the mock detail card and preview highlight.",
        status: "Ready",
      },
    ],
  },
  {
    title: "Responsive layout",
    items: [
      {
        label: "Desktop and narrow screens remain contained",
        expectedBehavior: "Panels stack cleanly, preserve min-w-0 containment, and avoid horizontal overflow.",
        status: "Manual check",
      },
    ],
  },
  {
    title: "Safety checks",
    items: [
      {
        label: "Production paths stay untouched",
        expectedBehavior: "No real editor, public renderer, API, Supabase, Google Sheets, webhook, or tracking code.",
        status: "Safety guard",
        note: "Manual grep plus lint/build guard.",
      },
    ],
  },
];

export const alignOptions: TextAlign[] = ["left", "center", "right"];
export const lockTypeOptions: LockType[] = ["none", "code", "age", "sensitive"];
export const pageStatusOptions: PageStatus[] = ["Draft", "Published", "Scheduled"];
export const pageVisibilityOptions: PageVisibility[] = ["Public", "Hidden", "Password protected"];
export const pageLanguageOptions: PageLanguage[] = ["Thai", "English"];
export const analyticsTimeRangeOptions: AnalyticsTimeRange[] = ["Today", "7 days", "30 days", "90 days"];
export const formFieldTypeOptions: FormFieldType[] = [
  "text",
  "textarea",
  "email",
  "phone",
  "select",
  "radio",
  "checkbox",
  "date",
  "file URL",
];
export const submissionDestinationOptions: SubmissionDestination[] = [
  "Mock inbox",
  "Email notification mock",
  "Google Sheets mock",
  "Webhook mock",
];
export const mockToday = "2026-05-20";
export const productionOrigin = "https://support.bn9.one";
